import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import Dashboard from '../components/Dashboard'
import { DEMO_MODE, supabase } from '../lib/supabase'
import { DEMO_BY_TOKEN, DEMO_PAYLOAD } from '../lib/demoData'
import type { SharedPayload } from '../lib/types'

/**
 * The read-only page Allison texts to her clients: /t/<share token>
 *
 * No login. The token IS the credential, so it must stay unguessable — it is a
 * v4 uuid generated by Postgres. This page never touches a table; it calls
 * get_shared_transaction(), which is the only thing anonymous visitors can do.
 */
export default function ClientView() {
  const { token } = useParams<{ token: string }>()
  const [data, setData] = useState<SharedPayload | null>(null)
  const [state, setState] = useState<'loading' | 'ok' | 'notfound' | 'error'>('loading')

  useEffect(() => {
    let cancelled = false

    async function load() {
      if (DEMO_MODE || !supabase) {
        setData(DEMO_BY_TOKEN[token ?? 'demo'] ?? DEMO_PAYLOAD)
        setState('ok')
        return
      }
      const { data: payload, error } = await supabase
        .rpc('get_shared_transaction', { p_token: token })

      if (cancelled) return
      if (error) {
        console.error(error)
        setState('error')
      } else if (!payload) {
        setState('notfound')
      } else {
        setData(payload as SharedPayload)
        setState('ok')
      }
    }

    load()
    return () => { cancelled = true }
  }, [token])

  if (state === 'loading') {
    return <div className="centered"><div className="spinner" /></div>
  }

  if (state === 'notfound') {
    return (
      <div className="centered">
        <div>
          <div className="wordmark" style={{ fontSize: 15, marginBottom: 14 }}>Not found</div>
          <p className="muted" style={{ maxWidth: 340, lineHeight: 1.7 }}>
            This link isn’t active. It may have been replaced with a newer one,
            or the transaction has been closed out. Reach out to your agent for
            an updated link.
          </p>
        </div>
      </div>
    )
  }

  if (state === 'error' || !data) {
    return (
      <div className="centered">
        <div>
          <div className="wordmark" style={{ fontSize: 15, marginBottom: 14 }}>
            Something went wrong
          </div>
          <p className="muted" style={{ maxWidth: 340, lineHeight: 1.7 }}>
            We couldn’t load this transaction. Try refreshing the page.
          </p>
        </div>
      </div>
    )
  }

  return (
    <>
      {DEMO_MODE && (
        <div className="demobar">
          Demo data — no database connected yet. Everything here is sample content.
        </div>
      )}
      <Dashboard data={data} editable={false} />
    </>
  )
}
